name = "iphey"
# Pages configuration
pages_build_output_dir = "apps/web-next/out"

# Cloudflare Pages compatibility
compatibility_date = "2024-09-23"

# Environment variables
[vars]
NODE_ENV = "production"
